# Generated by Django 2.2.6 on 2019-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_tag', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=512)),
                ('price', models.FloatField()),
            ],
        ),
    ]
